TrainingMgt/TrainingManagement/Controllers/DefaultController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainingManagement.DAL;
using System.Data;
using TrainingManagement.Models;

namespace TrainingManagement.Controllers
{
    public class DefaultController : Controller
    {
        MenuMasterDAL menu = new MenuMasterDAL();
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MenuMaster()
        {
            //string JSONString = string.Empty;
            //JSONString = JsonConvert.SerializeObject(menu.getMenu());
            DataTable dt = menu.getMenu();
            List<Models.MenuMaster> MenuList = new List<Models.MenuMaster>();
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                MenuMaster Menu = new MenuMaster();
                Menu.ID = Convert.ToInt32(dt.Rows[i]["ID"]);
                Menu.Name = dt.Rows[i]["Name"].ToString();
                Menu.ParentID = Convert.ToInt32(dt.Rows[i]["ParentID"]);
                Menu.Submenu = Convert.ToInt32(dt.Rows[i]["Submenu"]);
                MenuList.Add(Menu);
            }
            return View("getMenu", MenuList);

        }
    }
}

TrainingMgt/TrainingManagement/Views/Shared/_Layout.cshtml
@model IEnumerable<TrainingManagement.Models.MenuMaster>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                @{foreach (var item in Model)
                                    {

                                        <li class="dropdown">
                                            @if (item.ParentID == 0)
                                            {
                                                if (item.Submenu > 0)
                                                {
                                                    @*@Html.ActionLink(@item.Name, "Index", item.Name, new { htmlAttributes = new { @class = "dropdown-toggle" ,data_toggle= "dropdown" } })*@
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                        @item.Name

                                                    </a>
                                                }
                                                else
                                                {
                                                    @Html.ActionLink(@item.Name, "Index", item.Name)
                                                    @*<a href="#">@item.Name</a>*@
                                                }

                                            }
                                            <ul class="dropdown-menu">
                                                @{ foreach (var firstitem in Model)
                                                    {
                                                        <li>
                                                            @if (firstitem.ParentID == item.ID)
                                                            {
                                                                <a href="#">@firstitem.Name</a>
                                                            }
                                                        </li>
                                                    }
                                                }
                                            </ul>

                                        </li>
                                    }

                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TrainingMgt/TrainingManagement/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>*@
            @Html.Action("MenuMaster", "Default")
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>