TrainingMgt/TrainingManagement/Models/Trainee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TrainingManagement.Models
{
    public class Trainee
    {
        public int SelectType { get; set; }

        public int TraineeId { get; set; }
        [Required(ErrorMessage ="Please Enter Name")]
        
        //[StringLength(200, ErrorMessage = "Name cannot be longer than 200 characters.")]
        public string Name { get; set; }
        
        public string Technology { get; set; }
      
        public int Experience { get; set; }
        //[Required(ErrorMessage = "Contact number is Required")]
        //[RegularExpression("[^0-9]", ErrorMessage = "Contact must be numeric")]
        //[MaxLength(10)]
        public string ContactNo { get; set; }
        //[EmailAddress(ErrorMessage ="Please Enter valid Email address")]
        [EmailAddress(ErrorMessage = "Please Enter valid Email address")]
        public string Email { get; set; }
        public int Deleted { get; set; }
    }
}

TrainingMgt/TrainingManagement/Controllers/TraineeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainingManagement.DAL;
using TrainingManagement.Models;
using System.Data;

namespace TrainingManagement.Controllers
{
    public class TraineeController : Controller
    {
        TraineeDAL tdal = new TraineeDAL();
        // GET: Trainee
        public ActionResult Index()
        {
            DataTable dt = tdal.GetTrainee();
            List<Models.Trainee> traineeList = new List<Models.Trainee>();
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                Trainee trainee = new Trainee();
                trainee.TraineeId = Convert.ToInt32(dt.Rows[i]["TraineeId"]);
                trainee.Name = dt.Rows[i]["Name"].ToString();
                trainee.Technology = dt.Rows[i]["Technology"].ToString();
                trainee.Experience = Convert.ToInt32(dt.Rows[i]["Experience"]);
                trainee.ContactNo = dt.Rows[i]["ContactNo"].ToString();
                trainee.Email = dt.Rows[i]["EmailID"].ToString();
                traineeList.Add(trainee);
            }
            return View(traineeList);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            Trainee trainee = new Trainee();
            DataTable dt = tdal.GetTrainee(id);
            trainee.TraineeId = Convert.ToInt32(dt.Rows[0]["TraineeId"]);
            trainee.Name = dt.Rows[0]["Name"].ToString();
            trainee.Technology = dt.Rows[0]["Technology"].ToString();
            trainee.Experience = Convert.ToInt32(dt.Rows[0]["Experience"]);
            trainee.ContactNo = dt.Rows[0]["ContactNo"].ToString();
            trainee.Email = dt.Rows[0]["EmailID"].ToString();

            return View("Edit", trainee);
        }

        [HttpPost]
        public ActionResult Create(Trainee trainee)
        {
            trainee.SelectType = 1;
            tdal.CRUD_Trainee(trainee);
            //return View("Index");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Trainee trainee)
        {
            trainee.SelectType = 2;
            tdal.CRUD_Trainee(trainee);
            // return RedirectToAction("Index");
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Trainee trainee = new Trainee();
            DataTable dt = tdal.GetTrainee(id);
            trainee.TraineeId = Convert.ToInt32(dt.Rows[0]["TraineeId"]);
            trainee.Name = dt.Rows[0]["Name"].ToString();
            trainee.Technology = dt.Rows[0]["Technology"].ToString();
            trainee.Experience = Convert.ToInt32(dt.Rows[0]["Experience"]);
            trainee.ContactNo = dt.Rows[0]["ContactNo"].ToString();
            trainee.Email = dt.Rows[0]["EmailID"].ToString();

            return View("Details", trainee);
        }

        [HttpGet]
        public ActionResult Delete(int id)
          {
            Trainee trainee = new Trainee();
            DataTable dt = tdal.GetTrainee(id);
            trainee.TraineeId = Convert.ToInt32(dt.Rows[0]["TraineeId"]);
            trainee.Name = dt.Rows[0]["Name"].ToString();
            trainee.Technology = dt.Rows[0]["Technology"].ToString();
            trainee.Experience = Convert.ToInt32(dt.Rows[0]["Experience"]);
            trainee.ContactNo = dt.Rows[0]["ContactNo"].ToString();
            trainee.Email = dt.Rows[0]["EmailID"].ToString();

            return View("Delete",trainee);
        }

        [HttpPost]
        public ActionResult Delete(int id,Trainee trainee)
        {
            //Trainee trainee=new Trainee();
            trainee.TraineeId = id;
            tdal.CRUD_Trainee(trainee);
            // return RedirectToAction("Index");
            return RedirectToAction("Index");
        }
    }
}

TrainingMgt/TrainingManagement/Views/Trainee/Create.cshtml
@model TrainingManagement.Models.Trainee

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="container">
            <hr />
            <form class="form-horizontal">

                <div class="panel panel-success">
                    <div class="panel-heading" style="text-align:center;">
                        <h2>Trainee Details</h2>
                    </div>
                    <div class="form-horizontal">

                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", id = "txtName" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Technology, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Technology, new { htmlAttributes = new { @class = "form-control", id = "txtTechnology" } })
                                @Html.ValidationMessageFor(model => model.Technology, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Experience, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Experience, new { htmlAttributes = new { @class = "form-control", id = "txtExperience" } })
                                @Html.ValidationMessageFor(model => model.Experience, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control", id = "txtContactNo" } })
                                @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", id = "txtEmail" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-primary" id="btnSave" />

                                @Html.ActionLink("Back to List", "Index", "Trainee", htmlAttributes: new { Style = "margin-left: 46px;" })

                            </div>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    }
    <script type="text/javascript">
         $(document).ready(function() {  
        $("#btnSave").click(function() {  
            if ($('#txtName').val() == "") {
//alert("Enter the Name");
                MessageEvent("Enter the Name");
        }
        });  
    });  
        
        

            
        </script>

</body>
</html>

TrainingMgt/TrainingManagement/Views/Trainee/Delete.cshtml
@model TrainingManagement.Models.Trainee

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>

    <div class="container">
        <form class="form-horizontal">
            <hr />
            <div class="panel  panel-success">
                <div class="panel-heading" style="text-align:center;">
                    <h2> Trainer Details</h2>
                </div>

                <div class="alert alert-danger" role="alert"><h6 style="margin-top: -6px; margin-bottom: -13px;">Are you sure you want to delete this?</h6></div>
                <hr />
                <dl class="dl-horizontal">
                    @Html.HiddenFor(model => model.TraineeId, htmlAttributes: new { id = "txtID" })
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd id="txtName">
                        @Html.DisplayFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", id = "txtName" } })
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Technology)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Technology, new { htmlAttributes = new { @class = "form-control", id = "txtTechnology" } })
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Experience)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Experience, new { htmlAttributes = new { @class = "form-control", id = "txtExperience" } })
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ContactNo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control", id = "txtContactNo" } })
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", id = "txtEmail" } })
                    </dd>
                    <hr />
                    <dt></dt>
                    <dd>

                    </dd>
                </dl>


                @*<script type="text/javascript">
                    $("#btnDelete").on("click", function () {
                        var Trainee = {
                            "SelectType": 3,"TraineeID":$("#txtID").val(),"Name": $("#txtName").val(), "Technology": $("#txtTechnology").val(),
                            "Experience": $("#txtExperience").val(), "ContactNo": $("#txtContactNo").val(),"Email" :$("#txtEmail").val(),"Deleted":1
                        };

                        $.ajax({
                            url: '@Url.Action("Update","Trainee")',
                            type: "POST",
                            dataType: 'application/json; charset=utf-8',
                            data: Trainee,

                        beforeSend: function () {
                        },
                        success: function (data, status, jqXHR) {
                            alert("Successfully saved");
                        },
                        error: function (jqXHR, status, err) {
                            alert("Error");
                        },
                        complete: function (jqXHR, status) {

                        }
                    });
                });
                            </script>*@
            </div>
        </form>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-primary" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

TrainingMgt/TrainingManagement/Views/Trainee/Details.cshtml
@model TrainingManagement.Models.Trainee

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body>

    <div class="container">
        <form class="form-horizontal">
            <hr />
            <div class="panel  panel-success">
                <div class="panel-heading" style="text-align:center;">
                    <h2> Trainer Details</h2>
                </div>
                <hr />
                <dl class="dl-horizontal">

                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Technology)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Technology)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Experience)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Experience)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ContactNo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ContactNo)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>
                    <hr />
                    <dt></dt>
                    <dd>

                        @Html.ActionLink("Edit", "Edit", new { id = Model.TraineeId }) |
                        @Html.ActionLink("Back to List", "Index")

                    </dd>

                </dl>
            </div>
        </form>
    </div>


</body>
</html>

TrainingMgt/TrainingManagement/Views/Trainee/Edit.cshtml
@model TrainingManagement.Models.Trainee

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="container">
            <hr />
            <form class="form-horizontal">
                <div class="panel  panel-success">
                    <div class="panel-heading" style="text-align:center;">
                        <h2>Trainee Details</h2>
                    </div>
                    <div class="form-horizontal">

                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                        @Html.HiddenFor(model => model.TraineeId, htmlAttributes: new { id = "txtID" })

                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", id = "txtName" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Technology, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Technology, new { htmlAttributes = new { @class = "form-control", id = "txtTechnology" } })
                                @Html.ValidationMessageFor(model => model.Technology, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Experience, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Experience, new { htmlAttributes = new { @class = "form-control", id = "txtExperience" } })
                                @Html.ValidationMessageFor(model => model.Experience, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control", id = "txtContactNo" } })
                                @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", id = "txtEmail" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-primary" />
                                @Html.ActionLink("Back to List", "Index", "Trainee", htmlAttributes: new { Style = "margin-left: 46px;" })
                            </div>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    }
    @*<script type="text/javascript">
            $("#btnAdd").on("click", function () {
                var Trainee = {
                    "SelectType": 2,"TraineeID":$("#txtID").val(),"Name": $("#txtName").val(), "Technology": $("#txtTechnology").val(),
                    "Experience": $("#txtExperience").val(), "ContactNo": $("#txtContactNo").val(),"Email" :$("#txtEmail").val()
                };

                $.ajax({
                    url: '@Url.Action("Update","Trainee")',
                    type: "POST",
                    dataType: 'application/json; charset=utf-8',
                    data: Trainee,

                beforeSend: function () {
                },
                success: function (data, status, jqXHR) {
                    alert("Successfully saved");
                },
                error: function (jqXHR, status, err) {
                    alert("Error");
                },
                complete: function (jqXHR, status) {

                }
            });
        });
                        </script>*@




</body>
</html>

TrainingMgt/TrainingManagement/Views/Trainee/Index.cshtml
@model IEnumerable<TrainingManagement.Models.Trainee>

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <hr />
        <form class="form-horizontal">
            <div class="panel panel-success">
                <div class="panel-heading" style="text-align:center;">
                    <h2>Trainee Details</h2>
                </div>
                <p>
                    @Html.ActionLink("Create New", "Create")
                </p>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Technology)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Experience)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ContactNo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>

                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Technology)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Experience)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ContactNo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.TraineeId }) |
                                @Html.ActionLink("Details", "Details", new { id = item.TraineeId }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.TraineeId })
                            </td>
                        </tr>
                    }

                </table>

            </div>
        </form>
    </div>
</body>
</html>